CREATE TABLE IF NOT EXISTS WORK_TIME_SETTINGS
(
    ID          BIGINT AUTO_INCREMENT,
    STATIC_HOUR INT,
    ACTIVE      BIT(1),

    PRIMARY KEY (ID)
) CHARACTER
      SET utf8
  DEFAULT COLLATE utf8_unicode_ci;
