CREATE TABLE IF NOT EXISTS EMPLOYEE_GROUPS
(
    ID                  BIGINT AUTO_INCREMENT,
    CREATE_DATE         DATETIME,
    CREATE_BY           VARCHAR(256),
    DELETE_DATE         DATETIME,
    DELETED_BY          VARCHAR(256),
    NAME                VARCHAR(256),
    ACTIVE              BIT(1),

    PRIMARY KEY (ID)
) CHARACTER
      SET utf8
  DEFAULT COLLATE utf8_unicode_ci;

ALTER TABLE EMPLOYEES ADD COLUMN EMPLOYEE_GROUP_ID BIGINT;

ALTER TABLE EMPLOYEES ADD CONSTRAINT FK_EMPLOYEE_GROUP_ID_EMPLOYEES FOREIGN KEY (EMPLOYEE_GROUP_ID) REFERENCES EMPLOYEE_GROUPS (ID)