ALTER TABLE carpenter.OFFERS DROP COLUMN WORK_DATE_TO;
ALTER TABLE carpenter.OFFERS DROP COLUMN BUILDING_DIMENSION;
ALTER TABLE carpenter.OFFERS ADD COLUMN FORENAME_OF_CALLING VARCHAR(128);
ALTER TABLE carpenter.OFFERS ADD COLUMN DESCRIPTION VARCHAR(8000);
ALTER TABLE carpenter.OFFERS ADD COLUMN COMPANY_NAME VARCHAR(256);