CREATE TABLE IF NOT EXISTS AUDIT_TRIALS
(
    ID          BIGINT AUTO_INCREMENT,
    CREATE_DATE DATETIME,
    CREATE_BY   VARCHAR(128),
    DELETE_DATE DATETIME,
    DELETED_BY  VARCHAR(128),
    EMPLOYEE_ID BIGINT,
    CLIENT_IP   VARCHAR(56),

    CONSTRAINT FK_EMPLOYEE_ID_EMPLOYEES FOREIGN KEY (EMPLOYEE_ID) REFERENCES carpenter.EMPLOYEES (ID),

    PRIMARY KEY (ID)
) CHARACTER
      SET utf8
  DEFAULT COLLATE utf8_unicode_ci;
