CREATE TABLE IF NOT EXISTS COMPANY
(
    ID          BIGINT AUTO_INCREMENT,
    CREATE_DATE DATETIME,
    CREATE_BY     VARCHAR(256),
    DELETE_DATE DATETIME,
    DELETED_BY   VARCHAR(256),
    NAME        VARCHAR(100),
    CITY        VARCHAR(100),
    POSTAL_CODE VARCHAR(10),
    STREET      VARCHAR(100),
    COUNTRY     VARCHAR(64),
    EMAIL       VARCHAR(256),
    PHONE       VARCHAR(15),
    HIDDEN      BIT(1),

    PRIMARY KEY (ID)
) CHARACTER
      SET utf8
  DEFAULT COLLATE utf8_unicode_ci;