CREATE TABLE IF NOT EXISTS EMPLOYEE_GROUPS
(
    ID             BIGINT AUTO_INCREMENT,
    CREATE_DATE    DATETIME,
    CREATE_BY      VARCHAR(256),
    DELETE_DATE    DATETIME,
    DELETED_BY     VARCHAR(256),
    NAME           VARCHAR(256),
    PRESENT_CLIENT BIGINT,

    CONSTRAINT FK_CLIENT_ID_EMPLOYEE_GROUPS FOREIGN KEY (PRESENT_CLIENT) REFERENCES CLIENTS (ID),

    PRIMARY KEY (ID)
) CHARACTER
      SET utf8
  DEFAULT COLLATE utf8_unicode_ci;

ALTER TABLE EMPLOYEES
    ADD COLUMN EMPLOYEE_GROUP_ID BIGINT;

ALTER TABLE EMPLOYEES
    ADD CONSTRAINT FK_EMPLOYEE_GROUP_ID_EMPLOYEES FOREIGN KEY (EMPLOYEE_GROUP_ID) REFERENCES EMPLOYEE_GROUPS (ID);

ALTER TABLE EMPLOYEES DROP FOREIGN KEY FK_CLIENT_EMPLOYEE;
ALTER TABLE EMPLOYEES DROP COLUMN PRESENT_CLIENT;