CREATE TABLE IF NOT EXISTS CLIENTS
(
    ID                  BIGINT AUTO_INCREMENT,
    CREATE_DATE         DATETIME,
    CREATE_BY           VARCHAR(128),
    DELETE_DATE         DATETIME,
    DELETED_BY          VARCHAR(128),
    NAME                VARCHAR(128),
    NIP                 VARCHAR(128),
    EMAIL               VARCHAR(256),
    PHONE_NUMBER        VARCHAR(56),
    WEB_SITE            VARCHAR(256),
    BANK_ACCOUNT_NUMBER VARCHAR(128),
    CITY                VARCHAR(128),
    POSTAL_CODE         VARCHAR(128),
    STREET              VARCHAR(128),
    STREET_NUMBER       VARCHAR(128),
    HOUSE_NUMBER        VARCHAR(128),
    COUNTRY             VARCHAR(128),
    COMPANY_ID          BIGINT,

    CONSTRAINT FK_COMPANY_ID_CLIENTS FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (ID),

    PRIMARY KEY (ID)
) CHARACTER
     SET utf8
DEFAULT COLLATE utf8_unicode_ci;
