CREATE TABLE IF NOT EXISTS EMPLOYEE_ROLES
(
    ID   BIGINT AUTO_INCREMENT,
    ROLE VARCHAR(56),

    CONSTRAINT FK_EMPLOYEES_ID_EMPLOYEE_ROLES FOREIGN KEY (ID) REFERENCES EMPLOYEES (ID),

   PRIMARY KEY (ID, ROLE)
)