CREATE TABLE IF NOT EXISTS WORKING_DAYS
(
    ID          BIGINT AUTO_INCREMENT,
    CREATE_DATE DATETIME,
    CREATE_BY   VARCHAR(128),
    DELETE_DATE DATETIME,
    DELETED_BY  VARCHAR(128),
    DAY         DATETIME,
    HOURS       INT,
    CLIENT_ID   BIGINT,
    EMPLOYEE_ID BIGINT,
    EDIT_DATE   DATETIME,

    CONSTRAINT FK_CLIENT_WORKING_DAY FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS (ID),
    CONSTRAINT FK_EMPLOYEE_WORKING_DAY FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (ID),

    PRIMARY KEY (ID)
);
