CREATE TABLE IF NOT EXISTS AUDIT_TRAILS
(
    ID          BIGINT AUTO_INCREMENT,
    CREATE_DATE DATETIME,
    CREATE_BY   VARCHAR(256),
    DELETE_DATE DATETIME,
    DELETED_BY  VARCHAR(256),
    ACTIVITY    VARCHAR(32),
    EMPLOYEE_ID BIGINT,

    CONSTRAINT FK_EMPLOYEE_ID_AUDIT_TRAILS FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (ID),

    PRIMARY KEY (ID)

) CHARACTER SET utf8 DEFAULT COLLATE utf8_unicode_ci;
